DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
id SERIAL4 PRIMARY KEY,
NAME VARCHAR (255),
GENRE VARCHAR (255)
);

CREATE TABLE albums (
id SERIAL4 PRIMARY KEY,
NAME VARCHAR (255),
YEAR INT4,
artist_id INT4 REFERENCES artists(id)
)